logging:
  level:
    root: DEBUG
    tk.mybatis: DEBUG
    com.yunya: DEBUG
    com.yunya365: DEBUG

server:
  port: 8203

spring:
  application:
    name: yunya-clinic-base
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
  datasource:
    host: 192.168.31.90
    port: 3306
    username: sa
    password: Admin001!
    name: dev_yunya_clinc_base
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.31.90
    port: 6379
    password: foobared
    database: 2
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.215:8848

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yunya.models.clinic_base
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true
# 配置swagger
swagger:
  enabled: true
  base-package: com.yunya.modules.clinic_base
  title: yunya-clinic-base
  version: 1.0.0.SNAPSHOT
  description: 诊所相关业务 (网关地址：/api/clinic/base/**)
  contact:
    name: yunya-clinic-base

#设置hystrix超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
# 负载均衡
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false




