server:
  port: 8203

spring:
  application:
    name: yunya-clinic-base
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.31.90:3306/yunya_clinc_base?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: sa
    password: Admin001!
  redis:
    host: 192.168.31.90
    port: 6379
    password: foobared
    database: 2
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.215:8848

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yunya.models.system
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true
# 配置swagger
swagger:
  enabled: true
  base-package: com.yunya.modules.clinic.base
  title: yunya-clinic-base
  version: 1.0.0.SNAPSHOT
  description: 结算统计 (网关地址：/api/clinic/base/**)
  contact:
    name: yunya-clinic-base

#设置hystrix超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000




