spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.215:8848
      config:
        server-addr: 192.168.31.215:8848

  rabbitmq:
    host: 192.168.31.215
    port: 5672
    username: admin
    password: admin
# 日志打印级别
logging:
  level:
    # tk.mybatis: DEBUG
    com.yunya.auth: debug