spring.profiles.active=dev

server.port=8998
spring.application.name=rabbit-mq
spring.cloud.nacos.discovery.server-addr=192.168.31.215:8848

spring.datasource.url=jdbc:mysql://192.168.31.90:3306/yunya_system?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
spring.datasource.username=sa
spring.datasource.password=Admin001!
spring.datasource.driver-class-name=com.mysql.jdbc.Driver


auth.serviceId=yunya-auth
auth.user.token-header=Authorization
auth.client.token-header=x-client-token
auth.client.id=rabbit-mq  #不填则默认读取spring.application.name
auth.client.secret=123456
