spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.104.167.157:8848
        ip: 47.122.37.218

  rabbitmq:
    host: 114.215.203.158
    port: 5672
    username: admin
    password: admin
