logging:
  level:
    root: info
    com.yunya: info
    com.yunya365.mini: info
# 开发环境，nacos连215开发环境
spring:
  datasource:
    host: community.yunya365.com
    port: 3306
    username: sa
    password: Admin001!
    name: test_yunya_discount

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.215:8848
      config:
        server-addr: 192.168.31.215:8848

  redis:
    database: 2
    host: 192.168.31.90
    port: 6379
    password: foobared

domainUrl: http://test.ivy2.yunya365.com