# 测试环境
spring:
  datasource:
    host: community.yunya365.com
    port: 3306
    username: sa
    password: Admin001!
    name: test_yunya_discount

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.17.181:8848
      config:
        server-addr: 172.16.17.181:8848

  redis:
    database: 2
    host: 172.16.17.181
    port: 6379
    password: foobared

codeUrl:
  url: test.ivy2.yunya365.com/mobile