mapperserver:
  port: 8204

spring:
  application:
    name: employee-common
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.99.146.90:3306/yunya_clinic?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yunya.clinic.employee.common.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





