## 数据源连接
myjdbc:
    host: 192.168.31.90
    port: 3306
    username: sa
    password: Admin001!
    
## 数据库列表
mydb:
    report: dev_yunya_report
    system: dev_yunya_system
    patient: dev_yunya_patient_central
    discount: dev_yunya_discount
    treatment: dev_yunya_treatment
    employee-expand: dev_yunya_employee_expand
    appointment: dev_yunya_appointment_central
    treatment-other: dev_yunya_treatment_other

spring:
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
            config:
                server-addr: 127.0.0.1:8848
    redis:
        database: 3
        host: 192.168.31.90
        port: 6379
        password: foobared
    rabbitmq:
        host: 192.168.31.200
        port: 5672
        username: admin
        password: admin