spring:
    datasource:
        host: 192.168.31.90
        port: 3306
        username: sa
        password: Admin001!
        name: yunya_sms
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.31.215:8848
            config:
                server-addr: 192.168.31.215:8848
    redis:
        database: 2
        host: 192.168.31.90
        port: 6379
        password: foobared

wiki:
    host: yunya.test.utools.club
    notifyUrl: http://${wiki.host}/smsChargeOrder/notifyUrl
    redirectUrl: http://${wiki.host}/smsChargeOrder/redirectUrl