logging:
  level:
    com.yunya: DEBUG
    com.yunya365: DEBUG

server:
  port: 8104

spring:
  application:
    name: yunya-sms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    host: 192.168.31.90
    port: 3306
    username: sa
    password: Admin001!
    name: dev_yunya_sms
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.31.90
    port: 6379
    password: foobared
    database: 2
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.215:8848
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yunya.models.sms
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true
# 配置swagger
swagger:
  enabled: true
  base-package: com.yunya.modules.sms
  title: yunya-sms
  version: 1.0.0.SNAPSHOT
  description: 短信服务 (网关地址：/api/sms/**)
  contact:
    name: yunya-sms

#设置hystrix超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

aliyun:
  sms:
    accessKeyId: LTAI4G4rXydQDeSBZVx1kKgu
    accessSecret: 3tTNUGxktkRnCXzw7N0WGLf0XDRYbM
    aliyunDomain: dysmsapi.aliyuncs.com
    aliyunVersion: 2017-05-25

#    测试账号
#    accessKeyId: LTAI4G5V7ezDNNSSwyRTZJGm
#    accessSecret: WPpocSKOVgAFSXj3J8jMPQ5w3vH3qD

wiki:
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq+iElxN5xzGpN81gjLSzTROPWvYw+06YPyjG5bufC2NHjoaiISbdw6AnYcdIAT8g5dOgYB4SyDPSxvfje2k9CTUFbmNTTm5humwwbCz94UVJf6XwAWT1432WtW1VtrC3tK3BTM5v1rY4Bt7yjQPD/ao4ZGe/RsVOYIT7KGD8g/eLLuWPMcCJmCA0P8Vl65ouS3ioReLMWdEFwTGUNeWfA14/ki9Z+p1ldSz1uq+YE1eoYF18kyF3nlQbIjHdBhk9bRhodLBLrHP0SndawDUy6cdO7YbCsP2utYGVkWTxrCezszPhtGDfP9Jvvtw1J1yKCPNtfbDOz1uczhBO/u6P6QIDAQAB
    app: A55905710000004
    operatorId: 8fe21621f6e999a05c8f34226ff24791
    key: dc38b14f74888b3a88b51ace677cc3b8
    host: yunya.test.utools.club
    notifyUrl: http://${wiki.host}/smsChargeOrder/notifyUrl
    redirectUrl: http://${wiki.host}/smsChargeOrder/redirectUrl


