# 测试环境
spring:
  datasource:
    host: 47.104.167.157
    port: 3306
    username: sa
    password: Admin001!
    name: test_yunya_report

  cloud:
    nacos:
      discovery:
        server-addr: 47.104.167.157:8848
      config:
        server-addr: 47.104.167.157:8848

  redis:
    database: 2
    host: 47.104.167.157
    port: 6379
    password: foobared