# 测试环境
spring:
  datasource:
    host: community.yunya365.com
    port: 3306
    username: sa
    password: Admin001!
    name: test_yunya_treatment_other

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.17.177:8848
      config:
        server-addr: 172.16.17.177:8848

  redis:
    database: 2
    host: 172.16.17.177
    port: 6379
    password: foobared

# netty配置
netty:
  protocol: ws://test.ivy2.yunya365.com/api/treatment-netty
  discovery:
    server-addr: 172.16.17.177:8848