spring:
    datasource:
        host: community.yunya365.com
        port: 3306
        username: sa
        password: Admin001!
        name: ivy2_yunya_treatment_other

    cloud:
        nacos:
            discovery:
                server-addr: 192.168.31.215:8848
            config:
                server-addr: 192.168.31.215:8848

    redis:
        database: 2
        host: 192.168.31.90
        port: 6379
        password: foobared