spring:
    datasource:
        host: rm-bp18uejcrk63u04c9so.mysql.rds.aliyuncs.com
        port: 3306
        username: sa
        password: Admin001!
        name: yunya_employee_attend
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.100.80:8848
            config:
                server-addr: 192.168.100.80:8848
    redis:
        database: 2
        host: 192.168.100.79
        port: 6379
        password: foobared