# 测试环境
spring:
  datasource:
    host: community.yunya365.com
    port: 3306
    username: sa
    password: Admin001!
    name: test_yunya_employee_attend

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.17.177:8848
      config:
        server-addr: 172.16.17.177:8848

  redis:
    database: 2
    host: 172.16.17.177
    port: 6379
    password: foobared

# 推送
jpush:
  appKey: b863cff5a22b7edf2d06c404
  appMasterSecret: e0f0146be64e59643766d99b