server.port=8103
spring.application.name=yunya-employee-attend
spring.cloud.nacos.discovery.server-addr=192.168.31.215:8848
# feign≈‰÷√
feign.httpclient.enabled=false
feign.okhttp.enabled=true
#  ˝æ›ø‚¡¨Ω”
spring.datasource.url=jdbc:mysql://192.168.31.90:3306/yunya_employee_attend?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=CST
spring.datasource.username=sa
spring.datasource.password=Admin001!
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.redis.host=192.168.31.90
spring.redis.port=6379
spring.redis.password=foobared
spring.redis.database=2

spring.main.allow-bean-definition-overriding= true

# Mybatis
mybatis.mapper-locations=classpath:mapper/*.xml
# ¥Ú”°SQL
#logging.level.com.yunya.clinic.mapper=DEBUG
mybatis.mapperLocations=classpath:mapper/*Mapper.xml
mybatis.type-aliases-package=com.yunya.models.yunya-employee-attend
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl


#spring.cloud.nacos.config.namespace=dev
#spring.cloud.nacos.discovery.namespace=dev

# ≈‰÷√swagger
swagger.enabled= true
swagger.base-package= com.yunya.modules.employeeattend
swagger.title= yunya-employee-attend
swagger.version= 1.0.0.SNAPSHOT
swagger.description= ≈≈∞‡
swagger.contact.name=yunya-employee-attend