# 测试环境
spring:
  datasource:
    host: community.yunya365.com
    port: 3306
    username: sa
    password: Admin001!
    name: test_yunya_third_part

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.17.181:8848
      config:
        server-addr: 172.16.17.181:8848

  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: foobared

wechat:
  token: "yunya365"
  appId: "wx607bb75d3d685618"
  appSecret: "87f02d9135c6228409bc0d07be6e471d"
  encodingAESKey: "B4Pjk52AjOXzC37mtfYAzNa2X2UFp3AxhBkBaXj6Zu1"