logging:
  level:
    #        tk.mybatis: DEBUG
    com.yunya.modules.system: DEBUG
spring:
  application:
    name: yunya-clinic-appointment
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
  datasource:
    host: 192.168.31.90
    port: 3306
    name: yunya_appointment_central
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: sa
    password: Admin001!
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  #    rabbitmq:
  #        host: ${RABBIT_MQ_HOST:localhost}
  #        port:  ${RABBIT_MQ_PORT:5672}
  #        username: guest
  #        password: guest
  #    sleuth:
  #        enabled: true
  #          http:
  #            legacy:
  #              enabled: true
  redis:
    host: 192.168.31.90
    port: 6379
    password: foobared
    database: 2
  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.31.215:8848
        server-addr: localhost:8848
      config:
        namespace:
    sentinel:
      transport:
        dashboard: localhost:8080
sample:
  zipkin:
    discovery-client-enabled: false
    # When enabled=false, traces log to the console. Comment to send to zipkin

mybatis:
  basepackage: com.yunya.modules.appointment.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

server:
  port: 8110

# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

# 负载均衡
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

# 熔断
hystrix:
  threadpool:
    default:
      coreSize: 1000 #并发执行的最大线程数，默认10
      maxQueueSize: 1000 #BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000

# 配置swagger
swagger:
  enabled: true
  base-package: com.yunya.modules.appointment
  title: yunya-clinic-appointment
  version: 1.0.0.SNAPSHOT
  description: YUNYA患者预约后端服务
  contact:
    name: yunya-clinic-appointment

#redis-cache 相关
#redis:
#  pool:
#    maxActive: 300
#    maxIdle: 100
#    maxWait: 1000
#  host: 192.168.31.90
#  port: 6379
#  password: foobared
#  timeout: 2000
#  # 服务或应用名
#  sysName: yunya-clinic-appointment
#  enable: true
#  database: 2

# 暴露所以端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

