# 测试环境
spring:
  datasource:
    host: community.yunya365.com
    port: 3306
    username: sa
    password: Admin001!
    name: test_yunya_mall
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.17.177:8848
      config:
        server-addr: 172.16.17.177:8848
  redis:
    database: 2
    host: 172.16.17.177
    port: 6379
    password: foobared
  rabbitmq:
    host: 172.16.17.177
    port: 5672
    username: admin
    password: admin

wx:
  mini:
    appId: wx9d9209edf9634d94
    appSecret: 2cfb0904bc87f47fe73ddaaeb3d7359a
    corpId: ww853499493423c56e
    corpSecret: Rzu-GfUVBgsKXGyD_3Tipfq6I_usU-sodY4U8MF1Cts
    name: "云牙艾维口腔"
  pay:
    appId: wx9d9209edf9634d94
    michId: 1319671401
    appSecret: 2cfb0904bc87f47fe73ddaaeb3d7359a
    useSandboxEnv: false
    notifyUrl: http://test.ivy2.yunya365.com/api/ivy/mini/wx/notify
    refundNotifyUrl: http://test.ivy2.yunya365.com/api/ivy/mini/wx/refund/notify
    keyPath: classpath:static/apiclient_cert.p12

cloopen:
  sms:
    appId: aaf98f894fd44d15014fdfc9a7970cc3
    accountSid: 8a48b5514fd49643014fde330538197f
    accountToken: 7ceef6f6728e4f34b1efec64c97df79a
    host: app.cloopen.com
    port: 8883
    templateId: 1091107
    timeOut: 15

mp:
  domain: test.ivy2.yunya365.com
