# 测试环境
spring:
  datasource:
    host: rm-bp18uejcrk63u04c9.mysql.rds.aliyuncs.com
    port: 3306
    username: sa
    password: Admin001!
    name: yunya_mall
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.80:8848
      config:
        server-addr: 192.168.100.80:8848
  redis:
    database: 2
    host: 192.168.100.79
    port: 6379
    password: foobared
  rabbitmq:
    host: 192.168.100.79
    port: 5672
    username: admin
    password: admin

wx:
  mini:
    appId: wxb0616466dce8bd5b
    appSecret: 64da90b96969b100260e27b47d64d3ee
    corpId: wxd9689a169e95dfaf
    corpSecret: 8ROXjPVXT20Wnm-YAdDSMQ3ZuFRP94JGt5iz8kPoTIQ
    name: "艾维口腔"
  pay:
    appId: wxb0616466dce8bd5b
    michId: 1633172042
    appSecret: 64da90b96969b100260e27b47d64d3ee
    useSandboxEnv: false
    notifyUrl: http://ivy2.yunya365.com/api/ivy/mini/wx/notify
    refundNotifyUrl: http://ivy2.yunya365.com/api/ivy/mini/wx/refund/notify
    keyPath: classpath:static/prod/apiclient_cert.p12

cloopen:
  sms:
    appId: aaf98f894fd44d15014fdfc9a7970cc3
    accountSid: 8a48b5514fd49643014fde330538197f
    accountToken: 7ceef6f6728e4f34b1efec64c97df79a
    host: app.cloopen.com
    port: 8883
    templateId: 1091107
    timeOut: 15

mp:
  domain: ivy2.yunya365.com/mobile
