# 开发环境，nacos连215开发环境
spring:
  datasource:
    host: 192.168.31.90
    port: 3306
    username: sa
    password: Admin001!
    name: dev_yunya_mall

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.215:8848
      config:
        server-addr: 192.168.31.215:8848

  redis:
    database: 2
    host: 192.168.31.90
    port: 6379
    password: foobared

wx:
  mini:
    appId: wx9d9209edf9634d94
    appSecret: 2cfb0904bc87f47fe73ddaaeb3d7359a
    corpId: ww853499493423c56e
    corpSecret: Rzu-GfUVBgsKXGyD_3Tipfq6I_usU-sodY4U8MF1Cts
  pay:
    michId: 1319671401
    appSecret: 2cfb0904bc87f47fe73ddaaeb3d7359a
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq+iElxN5xzGpN81gjLSzTROPWvYw+06YPyjG5bufC2NHjoaiISbdw6AnYcdIAT8g5dOgYB4SyDPSxvfje2k9CTUFbmNTTm5humwwbCz94UVJf6XwAWT1432WtW1VtrC3tK3BTM5v1rY4Bt7yjQPD/ao4ZGe/RsVOYIT7KGD8g/eLLuWPMcCJmCA0P8Vl65ouS3ioReLMWdEFwTGUNeWfA14/ki9Z+p1ldSz1uq+YE1eoYF18kyF3nlQbIjHdBhk9bRhodLBLrHP0SndawDUy6cdO7YbCsP2utYGVkWTxrCezszPhtGDfP9Jvvtw1J1yKCPNtfbDOz1uczhBO/u6P6QIDAQAB
    operatorId: 8fe21621f6e999a05c8f34226ff24791
    appId: A55905710000004
    key: dc38b14f74888b3a88b51ace677cc3b8
    paymentChannel: WECHAT
    notifyUrl: xxx


cloopen:
  sms:
    appId: aaf98f894fd44d15014fdfc9a7970cc3
    accountSid: 8a48b5514fd49643014fde330538197f
    accountToken: 7ceef6f6728e4f34b1efec64c97df79a
    host: app.cloopen.com
    port: 8883
    templateId: 1091107
    timeOut: 15
