
#// 首次创建时需填写手机验证码。
#// AccessKeySecret只在创建时显示，不提供查询，请妥善保管。
#// 若AccessKey泄露或丢失，则需要创建新的AccessKey，最多可以创建2个AccessKey。
aliyun.oss.endpoint=http://oss-cn-hangzhou.aliyuncs.com
#aliyun.oss.endpoint=http://img.yunya365.com
aliyun.oss.access-key-id=LTAI4GL3SpbVMBDnzGRYz6GZ
aliyun.oss.access-key-secret=nQKA5iLUfMCPHH6Yy2UrBageveHmeh
aliyun.oss.bucket=yunya-backend

