spring:
    datasource:
        host: rm-bp18uejcrk63u04c9.mysql.rds.aliyuncs.com
        port: 3306
        username: sa
        password: Admin001!
        name: yunya_patient_central

    cloud:
        nacos:
            discovery:
                server-addr: 192.168.100.80:8848
            config:
                server-addr: 192.168.100.80:8848

    redis:
        database: 2
        host: 192.168.100.79
        port: 6379
        password: foobared


codeUrl:
    url: http://192.168.31.95:8080/mobile
# 自定义服务上线日期属性,用于解决兼容一代系统患者病历编号，二代系统上线之后，所有新添加的患者按照二代病历编号生成规则生成
serverInfo:
    onlineDateTime: "2021-02-01 06:00:00"