package com.yunya.feign.report.enums;

public enum MsgCategoryEnum {
    BaseBenefit,
    BaseCardSingle,
    BaseCardBatch,
    BaseEmployeeSchedule,
    BasePatientMemberOccurLog,
    BaseTariffInfo,
    BaseBillDetail,
    BaseCouponItem,
    BaseOrganization,
    BaseAccountItem,
    BasePatientMemberRelation,
    BaseTreatmentProcess,
    BaseBill,
    BaseCoupon,
    BasePatient,
    BaseRefundDetail,
    BaseUserPost,
    BaseBillPay,
    BaseBillPayDetail,
    BaseEmployee,
    BasePatientMember,
    BaseRefund,
    BaseVisitRemind,
}
