# 开发环境，nacos连215开发环境
spring:
  datasource:
    host: community.yunya365.com
    port: 3306
    username: sa
    password: Admin001!
    name: test_yunya_system

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.215:8848
      config:
        server-addr: 192.168.31.215:8848

  redis:
    database: 2
    host: 192.168.31.90
    port: 6379
    password: foobared

domainUrl: http://192.168.31.95

qzt:
  prefix: http://121.41.36.72:8010

bj:
  prefix: http://8.136.199.41:84
  appKey: 65028
  appSecret: cb2d6e93507a0ee800b8473e486b89ed34554aa2