# 勿动
# 数据库连接
spring:
  datasource:
    host: rm-bp18uejcrk63u04c9.mysql.rds.aliyuncs.com
    port: 3306
    username: sa
    password: Admin001!
    name: yunya_system
# 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.80:8848
      config:
        server-addr: 192.168.100.80:8848
# 缓存
  redis:
    database: 2
    host: 192.168.100.79
    port: 6379
    password: foobared

# 日志打印级别
logging:
  level:
    tk.mybatis: INFO
    com.yunya: INFO
    com.yunya365: INFO

domainUrl: http://ivy2.yunya365.com

qzt:
  prefix: https://www.aioclinic.com

bj:
  prefix: 8.136.250.65:127
  appKey: 65028
  appSecret: cb2d6e93507a0ee800b8473e486b89ed34554aa2