# 测试环境
spring:
  datasource:
    host: community.yunya365.com
    port: 3306
    username: sa
    password: Admin001!
    name: test_yunya_system

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.17.177:8848
      config:
        server-addr: 172.16.17.177:8848

  redis:
    database: 2
    host: 172.16.17.177
    port: 6379
    password: foobared

domainUrl: http://test.ivy2.yunya365.com

qzt:
  prefix: http://121.41.36.72:8010

bj:
  prefix: 8.136.199.41:84