server:
  port: 8203

spring:
  application:
    name: clinic-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.31.90:3306/yunya_system?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: sa
    password: Admin001!
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yunya.models.system
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





